REST API implementation.
velp/test-cloud-manager pull request #1
Opened 2021-02-26 18:44 UTC by Dmitry-Eremeev

@velp 
Please take a look ))

2021-02-27 15:49 UTC, velp requested changes
Общие замечания по заданию сейчас:
1. не совсем правильное оформление репозитория (документация в txt, файл env.file в корне)
2. сборка в docker только для тестовой среды разработчика, в прод такое не выкатишь (большой образ, кэш в образе, запуск крипта без WSGI, запуск от root);
3. то что указано в TODO определяет можно ли считать задание выполненным или нет;
4. много хардкода;
5. прямая работа с OpenStack API через requests;
6. создание подключения к БД на каждый запрос;
7. репозиторий не подготовлен для деплоя (нет Makefile или другого скрипта для реализации сборки, файл базы доставляется отдельно, что делать с миграциями и изменениями в базе не понятно, в k8s это приложение не запустить нормально);

По результатам ревью у меня осталось ощущение, что ты понимаешь, что и как должно быть сделано, но почему-то решил не делать или не успел (хотя ограничений по времени, фактически, не было).

2021-02-27 15:49 UTC, velp commented on rest_api/Dockerfile
> +RUN pip install -r /opt/rest_api/requirements.txt
Весь кэш сборки тоже поедет на прод?

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +#       it's better to take last 24 records and selects for one day from them.
Я бы назвал эти TODO ключевыми.

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +openstack_url = f"http://{os.getenv('OPENSTACK_HOST')}"
Если нам понадобится запустить это приложение на реальном кластере, то ничего не выйдет, потому что `http://`

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +                         f"user={os.getenv('DB_USER')} password={os.getenv('DB_PASSWORD')}"
Что будет если подключение к базе у нас с SSL?

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +    return result
Вместо ручной обработки запросов и работы с keystone лучше использовать готовую библиотеку из состава самого Openstack https://docs.openstack.org/python-keystoneclient/ocata/using-api-v3.html

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}:9696/v2.0/networks", headers={"X-Auth-Token": token})
Что будет если в следующей версии Openstack сменится URL API? Как можно решить проблему?

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/image/v2/images", headers={"X-Auth-Token": token})
Что будет если в следующей версии Openstack сменится URL API? Как можно решить проблему?

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/compute/v2.1/flavors/detail",
Что будет если в следующей версии Openstack сменится URL API? Как можно решить проблему?

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/compute/v2.1/servers/detail",
Что будет если в следующей версии Openstack сменится URL API? Как можно решить проблему?

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +    all_resources = globals()[function_to_get_resources](token)
Странное решение. Если хочется устранить дублирование кода и сделать решение модульным, то лучше заранее определить все варианты (либо в dict либо использовать class).

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +        return {"status": all_resources["status"], "error": f"get resource list failed: {all_resources['error']}"}
pep8 120?

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +    for item in all_resources["data"][resource_type]:
Если произошла ошибка, например, подключения или DNS, что увидит пользователь в ответе?

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +    response = requests.post(url=f"{openstack_url}/compute/v2.1/servers",
Хардкод URL, в следующем релизе он изменится, как можно решить проблему?

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +    if "error" in token:
Есть ли способ понять какая именно ошибка произошла? Чтобы пользователь понимал что случилось.

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +            time.sleep(3600)
В момент редеплоя приложения или простого рестарта получим ли мы дубликат данных в статистике? Или данные в базе будут всегда иметь промежуток снятия 3600 сек?

2021-02-27 15:49 UTC, velp commented on rest_api/env.list
> +SERVICE_OPENSTACK_PROJECT_NAME
Не вижу смысла держать этот файл в репе. Он работает только если не забыли указать при запуске флаг `--env-file`, а так как в репозитории нет Makefile с четко прописанной командой, или иного скрипта запуска, работать это не будет. Проверку необходимых env переменных надо делать в самом приложении, при инициализации конфига.

2021-02-27 15:49 UTC, velp commented on rest_api/core.py
> +    return {"status": response.status_code, "data": response.json()}
если запрос не удался, то тут вылетит traceback потому что данных в response не будет.

2021-02-27 15:49 UTC, velp commented on rest_api/rest_api.py
> +# TODO: us noSQL for api requests logging
То же замечание: это очень ключевые моменты, которые отделяют скрипт написанный на коленке от сервиса.

2021-02-27 15:49 UTC, velp commented on rest_api/rest_api.py
> +bottle.run(app, host="0.0.0.0", debug=os.getenv("REST_API_DEBUG_MODE"))
Если сервис требуется запустить на определенном адресе?

2021-02-27 15:49 UTC, velp commented on rest_api/rest_api.py
> +        connection = psycopg2.connect(core.db_connection_settings)
Если на каждый запрос мы будем создавать свое подключение, да еще и сразу же пытаться писать в базу данных, наше API очень быстро достигнет максимума производительности при параллельных запросах.

2021-02-27 15:49 UTC, velp commented on rest_api/rest_api.py
> +                return bottle.HTTPResponse(status=503,
хм, не совсем понял почему `error` в keystone запросе - это всегда проблема подключения (код 503 как раз про это)

2021-02-27 15:49 UTC, velp commented on rest_api/rest_api.py
> +    result = core.get_flavors(token=bottle.request.token)
Тут и далее в аналогичных вызовах, что произойдет когда получим traceback в запросу в OpenStack?

2021-02-27 15:49 UTC, velp commented on rest_api_db/Dockerfile
> +COPY init.sql /docker-entrypoint-initdb.d/
Как деплоймент инженеры будут катить это приложение на прод? Как будет вестись развитие базы данных в следующих версиях? Будет ставиться задача в духе "вот там докер образ новой версии, а вот тут файлик с голыми запросами которые надо выполнить в базу данных на проде руками"?

2021-02-27 15:49 UTC, velp commented on rest_api_db/init.sql
> +);
Эти таблицы базы данных будут очень сильно пухнуть. И хоть задание не указывает на это явно, но данные в базе нужны чтобы их иногда просматривать. Имеет ли смысл как-то оптимизировать структуру таблиц?

2021-03-01 18:52 UTC, Dmitry-Eremeev commented
> Общие замечания по заданию сейчас:
> 
> 1. не совсем правильное оформление репозитория (документация в txt, файл env.file в корне)

про документацию в txt - согласен.
по поводу env файлов:
в корне env файл, его надо сорсить перед запуском докер контейнеров (rest api и db). 
одни и те же переменные окружения и их значения нужны обоим контейнерам для связи между ними.
то есть этот енв нужен всем и поэтому в корне.

> 2. сборка в docker только для тестовой среды разработчика, в прод такое не выкатишь (большой образ, кэш в образе, запуск крипта без WSGI, запуск от root);

согласен

> 3. то что указано в TODO определяет можно ли считать задание выполненным или нет;

выполнения задачи заняло много времени и я выкатил минимально работающий вариант.
А чтобы не думали, что я думаю, что всё отлично сделано и лучше не бывает, то написал TODO )))))
согласен - нехорошо


> 4. много хардкода;

тут просьба примеры конкретные показать.

> 5. прямая работа с OpenStack API через requests;

я других способов работы с openstack api не знаю - просьба подсказать какие есть варианты ещё.
(в счёт не беру всякие клиенты типа openstack client, neutron и тд)

> 6. создание подключения к БД на каждый запрос;

согласен

> 7. репозиторий не подготовлен для деплоя (нет Makefile или другого скрипта для реализации сборки, файл базы доставляется отдельно, что делать с миграциями и изменениями в базе не понятно, в k8s это приложение не запустить нормально);

с деплоем согласен - нет автоматизации, а только инструкция с командами.
по поводу файла БД и миграций не понял - просьба разъяснить.
по поводу k8s не могу ответить - плохо знаю. надо разбираться...

> 8. не уверен что линтеры запускались по коду;

прям линтеры не запускал, но pep8 настроен в пайчарме и соблюдаю, что он требует от меня.
или есть какие-то конкретные примеры ?

> По результатам ревью у меня осталось ощущение, что ты понимаешь, что и как должно быть сделано, но почему-то решил не делать или не успел (хотя ограничений по времени, фактически, не было).

скорее всего не успел - много времени уже делаю.
вот и показал, что есть )))

2021-03-01 18:52 UTC, Dmitry-Eremeev commented on deploy.txt
> +docker rm -f rest_api_db rest_api
согласен

2021-03-01 18:54 UTC, Dmitry-Eremeev commented on deploy.txt
> +apt install docker.io (for ubuntu)
ок

2021-03-01 18:56 UTC, Dmitry-Eremeev commented on example_config_sh.txt
> +export SERVICE_OPENSTACK_PROJECT_NAME="demo"
нет,
это файлик сорсится, он не для чтения людьми. (точнее это пример файла, из которого делается настоящий файл енва как сеттинги в девстэк копируются из примера)
просто посетить окружение перезапуском контейнеров

2021-03-01 18:57 UTC, Dmitry-Eremeev commented on rest_api/Dockerfile
> +FROM python:3.9.2-buster
можно взять buster-slim или alpine или ещё легче чего-нибудь

2021-03-01 18:57 UTC, Dmitry-Eremeev commented on rest_api/Dockerfile
> +CMD python /opt/rest_api/rest_api.py
небезопасно и вообще плохо

2021-03-01 18:58 UTC, Dmitry-Eremeev commented on rest_api/Dockerfile
> +RUN pip install -r /opt/rest_api/requirements.txt
кэш надо удалять в конце сборки.

2021-03-01 18:58 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +#       it's better to take last 24 records and selects for one day from them.
согласен

2021-03-01 18:58 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +openstack_url = f"http://{os.getenv('OPENSTACK_HOST')}"
я вообще не понял почему нельзя.
не разбираюсь в вопросе - просьба разъяснить.

2021-03-01 18:59 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +                         f"user={os.getenv('DB_USER')} password={os.getenv('DB_PASSWORD')}"
ssl не учёл

2021-03-01 19:03 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    return result
спасибо.
но я почему-то подумал, что не должен пользоваться openstack инструментами, а типа сам должен заимплементить обращения к openstack api - зря значит так подумал.
так я мог вообще захардкодить обращения openstack клиента внутри моего рест апи  типа "openstack server list" )))))) я думал так нельзя

2021-03-01 19:03 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    return result
типа задание нарушу

2021-03-01 19:04 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}:9696/v2.0/networks", headers={"X-Auth-Token": token})
вообще я хз,но предполагаю, что есть определённый урл, по которому можно получить схему всех роутов, типа browsable api

2021-03-01 19:05 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    all_resources = globals()[function_to_get_resources](token)
согласен

2021-03-01 19:05 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/image/v2/images", headers={"X-Auth-Token": token})
плиз см. выше

2021-03-01 19:05 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/compute/v2.1/flavors/detail",
плиз см. выше

2021-03-01 19:05 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/compute/v2.1/servers/detail",
плиз см. выше

2021-03-01 19:06 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +        return {"status": all_resources["status"], "error": f"get resource list failed: {all_resources['error']}"}
ну так же можно до 120

2021-03-01 19:20 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    for item in all_resources["data"][resource_type]:
в этом случае произойдёт эксепшн, а юзеру вернётся ошибка 500 (так работает bottle).
но это конечно же нехорошо - лучше отдавать более конкретную ошибку юзеру.
Единственное, что может помочь юзеру, это то, что перед каждым обращением к какому-то ресурсу опенстэка сначала получается токен, а ошибки обращения к keystone обрабатываются в какой-то степени и соответственно обращений к другим ресурсам не будет т.к. токена нет.

except requests.exceptions.ConnectionError:

то есть если весь опенстэк упал, то об этом юзер узнает при получении токена.
Но ситуаций когда кейстоун доступен, а другие сервисы плохо работают - вероятность огромная.

2021-03-01 19:21 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    response = requests.post(url=f"{openstack_url}/compute/v2.1/servers",
плиз см. выше

2021-03-01 19:23 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    if "error" in token:
я полностью передаю текст ошибок от ресурсов пользователю при всех обращениях - то есть тупо проксирую от ресурса. своих сообщений добавляю минимум - только для ясности от какого ресурса идёт сообщение.

2021-03-01 19:31 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +            time.sleep(3600)
дубликата никогда не будет.
при отправке статистики в апи всегда время округляется до часа в меньшую сторону, т. е. 17:35:23 будет всегда 17:00:00.
то есть в случае рестарта или одновременной работы нескольких копий приложения в один час будет отправлятся статистика с одним и тем же таймстэмпом.
в бд таблице поле таймстэмпа уникальное, т.е при первом приходе статы с временем 17:00:00 запись произойдёт, при повтороной попытке записи с таким же временем в записи будет отказано.
то есть уникальность статы строго поддерживается на стороне БД. Но и АПИ также помогает в этом.
Не уверен, что этот вариант оптимальный когда бд будет огромная.
Лучше наверно было бы написать функцию в бд, которая при попытке записи брала бы последнюю запись и смотрела если она больше часа, то записывала бы.

2021-03-01 19:34 UTC, Dmitry-Eremeev commented on rest_api/env.list
> +SERVICE_OPENSTACK_PROJECT_NAME
я сделал этот файлик, чтоб в командлайне не указывать тысячу переменных,
сам по себе файлик не поможет конечно.
про проверку конфига на старте приложения - согласен.

2021-03-01 19:38 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    return {"status": response.status_code, "data": response.json()}
если например ошибка соединения или днс, то будет эксепшн и юзеру вернётся 500 (bottle так делает) - не очень хорошо, что не конкретная ошибка.
если вернётся сообщение об ошибке от openstack, в теле респонса будет сообщение от опенстэка и юзеру оно вернётся

2021-03-01 19:39 UTC, Dmitry-Eremeev commented on rest_api/rest_api.py
> +# TODO: us noSQL for api requests logging
согласен полностью

2021-03-01 19:41 UTC, Dmitry-Eremeev commented on rest_api/rest_api.py
> +bottle.run(app, host="0.0.0.0", debug=os.getenv("REST_API_DEBUG_MODE"))
этот адрес - это все внешние интерфейсы докер контейнера,
а по факту сервис будет доступен по интерфейсу и по порту, по которым был проброшен при запуске контейнера
docker run --name rest_api --env-file rest_api/env.list -p $REST_API_HOST:$REST_API_PORT:8080 -d rest_api

то есть по этим 
$REST_API_HOST:$REST_API_PORT

2021-03-01 19:41 UTC, Dmitry-Eremeev commented on rest_api/rest_api.py
> +        connection = psycopg2.connect(core.db_connection_settings)
согласен

2021-03-01 19:45 UTC, Dmitry-Eremeev commented on rest_api/rest_api.py
> +                return bottle.HTTPResponse(status=503,
не понял коммента.
вообще я сам это поле error наполняю:
   try:
        keystone_response = requests.post(url=f"{openstack_url}/identity/v3/auth/tokens?nocatalog",
                                          json=token_data)
    except requests.exceptions.ConnectionError:
        result["error"] = f"keystone is not available."
    else:
        if keystone_response.status_code != 201:
            result["error"] = f"keystone error: {keystone_response.text}"
        else:
            result["token"] = keystone_response.headers["X-Subject-Token"]
    return result

и я сам решил, что апи будет возвращать 503 если по какой-то причине токен не получилось достать.
то есть это на уровне моего апи.

2021-03-01 19:45 UTC, Dmitry-Eremeev commented on rest_api/rest_api.py
> +    result = core.get_flavors(token=bottle.request.token)
рест апи вернёт общую ошибку 500 - это не очень хорошо, но и приложение не упадёт

2021-03-01 19:49 UTC, Dmitry-Eremeev commented on rest_api_db/Dockerfile
> +COPY init.sql /docker-entrypoint-initdb.d/
этот файлик не надо выполнять руками.
при запуске контейнера postgres будет запускаться автоматически скриптик sql и таблицы будут создаваться.
руками никто ничего не будет делать, надо только выполнить:

docker run --name rest_api_db -e POSTGRES_PASSWORD=$DB_PASSWORD -e POSTGRES_DB=$DB_NAME -e POSTGRES_USER=$DB_USER -p $DB_HOST:$DB_PORT:5432 -d rest_api_db

а вот как будет мигрировать уже существующая БД - это я не думал.

2021-03-01 19:50 UTC, Dmitry-Eremeev commented on rest_api_db/init.sql
> +);
оптимизировать наверно надо, но я не знаю как - надо подумать

2021-03-01 19:55 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +            time.sleep(3600)
ну и не совсем час разница может быть.
может прийти стата в 17.59 и в 18.01, а потом в 19.59 - но думаю непринципиально

2021-03-01 19:59 UTC, Dmitry-Eremeev commented on rest_api/rest_api.py
> +                return bottle.HTTPResponse(status=503,
но вообще всегда возвращать 503 - это плохо, т.к. причины могут быть разные.
но всегда возвращаю текст от кейстоун - это поможет юзеру.

2021-03-02 15:07 UTC, velp commented on rest_api/Dockerfile
> +FROM python:3.9.2-buster
👍

2021-03-02 15:07 UTC, velp commented on example_config_sh.txt
> +export SERVICE_OPENSTACK_PROJECT_NAME="demo"
тогда был смысл делать его с расширением `.sh`

2021-03-02 15:08 UTC, velp commented on rest_api/core.py
> +openstack_url = f"http://{os.getenv('OPENSTACK_HOST')}"
Насколько я вижу по коду `http://` - это захардкоженая строка сейчас, то есть если мы захоим идти по HTTPS нам надо менять код. Чтобы такого не было стоит в переменную OPENSTACK_HOST передавать весь URI целиком в формате `<protocol://url>`

2021-03-02 15:09 UTC, velp commented on rest_api/core.py
> +                         f"user={os.getenv('DB_USER')} password={os.getenv('DB_PASSWORD')}"
тут аналогично с OPENSTACK_HOST - в переменную имеет смысл передавать всю строку подключения к базе со всеми параметрами аля `postgresql://[user[:password]@][host][:port][,...][/dbname][?param1=value1&...]` (https://www.postgresql.org/docs/10/libpq-connect.html)

2021-03-02 15:13 UTC, Dmitry-Eremeev commented on example_config_sh.txt
> +export SERVICE_OPENSTACK_PROJECT_NAME="demo"
я специально сделал расширение НЕ sh, чтобы ни у кого не было желания его засорсить, потому как это пример только.
юзер делает
cp example_config_sh.txt config.sh
а потом свои значения в свой енв (config.sh) записывает.

2021-03-02 15:13 UTC, velp commented on rest_api/core.py
> +    return result
Не путай команды CLI (те что ты вызываешь руками в shell) с клиентскими библиотеками вроде keystoneauthclient, neutronclient, novaclient и т.д. Команды CLI конечно из кода вызывать не надо, а вот использование библиотек позволяет тебе избежать целого ряда проблем:
1. не беспокоиться об изменении URLов в OpenStack API
2. не хардкодить URLы у себя в коде
3. не беспокоиться об изменившихся параметрах и передаваемом теле
4. не беспокоиться об актуальной версии API
5. не беспокоиться о env переменных самого сервиса (когда например можно определить OS_AUTH_URL прям для твоего сервиса и тем самым сказать твоему приложению ходить в другой кластер, например, для теста)

2021-03-02 15:14 UTC, velp commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}:9696/v2.0/networks", headers={"X-Auth-Token": token})
Этот вопрос ссылался на идею использования клиентских библиотек https://github.com/velp/test-cloud-manager/pull/1#discussion_r585649054

2021-03-02 15:14 UTC, velp commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/image/v2/images", headers={"X-Auth-Token": token})
Этот вопрос ссылался на идею использования клиентских библиотек https://github.com/velp/test-cloud-manager/pull/1#discussion_r585649054

2021-03-02 15:14 UTC, velp commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/compute/v2.1/flavors/detail",
Этот вопрос ссылался на идею использования клиентских библиотек https://github.com/velp/test-cloud-manager/pull/1#discussion_r585649054

2021-03-02 15:14 UTC, velp commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/compute/v2.1/servers/detail",
Этот вопрос ссылался на идею использования клиентских библиотек https://github.com/velp/test-cloud-manager/pull/1#discussion_r585649054

2021-03-02 15:15 UTC, velp commented on rest_api/core.py
> +        return {"status": all_resources["status"], "error": f"get resource list failed: {all_resources['error']}"}
это был уточняющий вопрос. Правильно в принципе и то и то, а скорее даже правильнее то что принято в конкретной команде/компании. У нас просто используется 80 поэтому бросилось в глаза.

2021-03-02 15:16 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +openstack_url = f"http://{os.getenv('OPENSTACK_HOST')}"
понял - согласен

2021-03-02 15:17 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +                         f"user={os.getenv('DB_USER')} password={os.getenv('DB_PASSWORD')}"
понял

2021-03-02 15:18 UTC, velp commented on rest_api/core.py
> +    for item in all_resources["data"][resource_type]:
Код 500 в REST API обозначает не предвиденное событие. Если ты можешь в своем приложении распознать что произошло, то стоит конечному пользователю давать конкретную расшифровку с корректным кодом. Большинство проектировщиков фронта вообще никогда не показывают тело ответа при получении кода 500. Так же как и дополнительные прокси которые стоят между твоим API и клиентом могут резать это тело если код 500 (это делается для безопасности, чтобы случайно не вывалить текст ошибки из базы с приватными данными).

2021-03-02 15:18 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    return result
понял.

2021-03-02 15:18 UTC, velp commented on rest_api/core.py
> +    response = requests.post(url=f"{openstack_url}/compute/v2.1/servers",
Этот вопрос ссылался на идею использования клиентских библиотек https://github.com/velp/test-cloud-manager/pull/1#discussion_r585649054

2021-03-02 15:18 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}:9696/v2.0/networks", headers={"X-Auth-Token": token})
понял

2021-03-02 15:18 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/image/v2/images", headers={"X-Auth-Token": token})
понял

2021-03-02 15:19 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/compute/v2.1/flavors/detail",
ок

2021-03-02 15:19 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    response = requests.get(url=f"{openstack_url}/compute/v2.1/servers/detail",
ок

2021-03-02 15:20 UTC, velp commented on rest_api/core.py
> +    if "error" in token:
Тут смысл примерно такой же как и с кодом 500 (https://github.com/velp/test-cloud-manager/pull/1#discussion_r585653113) можешь ли ты быть уверен что там в ответе не прилетит какая-то приватная информация? Знаешь ли ты все возможные тексты ответов от опенстека (которые есть сейчас и будут в будущем)? Думаю что нет. Поэтому имеет смысл переписывать текст и распозновать ошибки в своем коде.

2021-03-02 15:20 UTC, velp commented on rest_api/core.py
> +            time.sleep(3600)
хм, да. В принципе рабочее решение для этого задания.

2021-03-02 15:21 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +        return {"status": all_resources["status"], "error": f"get resource list failed: {all_resources['error']}"}
понял

2021-03-02 15:21 UTC, velp commented on rest_api/core.py
> +    return {"status": response.status_code, "data": response.json()}
Тот же ответ что и в https://github.com/velp/test-cloud-manager/pull/1#discussion_r585653113 - надо распознавать и экранировать. Клиенту незачем знать нашу архитектуру и приватную информацию.

2021-03-02 15:22 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    for item in all_resources["data"][resource_type]:
понял - согласен

2021-03-02 15:23 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    response = requests.post(url=f"{openstack_url}/compute/v2.1/servers",
ок

2021-03-02 15:23 UTC, velp commented on rest_api/rest_api.py
> +bottle.run(app, host="0.0.0.0", debug=os.getenv("REST_API_DEBUG_MODE"))
Ну вот я и не смог найти где у тебя в коде используется переменная `REST_API_HOST` а нашел только хардкод 0.0.0.0. Вероятно ты забыл использовать эту переменную тут.

2021-03-02 15:24 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    if "error" in token:
да, согласен, но это значительная работа  - обрабатывать все возможные варианты ошибок )))

2021-03-02 15:24 UTC, velp commented on rest_api/rest_api.py
> +                return bottle.HTTPResponse(status=503,
Тот же смысл что и в ответе https://github.com/velp/test-cloud-manager/pull/1#discussion_r585653113 - надо скрыть от клиента потенциально приватную информацию.

2021-03-02 15:25 UTC, velp commented on rest_api_db/Dockerfile
> +COPY init.sql /docker-entrypoint-initdb.d/
Этот вопрос был направлен в сторону использования alembic (https://alembic.sqlalchemy.org/en/latest/).

2021-03-02 15:26 UTC, velp commented on rest_api_db/init.sql
> +);
Вопрос был направлен на расстановку индексов в базе данных.

2021-03-02 15:30 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    if "error" in token:
я имею в виду, что обработка различных ошибок увеличивается в процессе развития приложения,а не на самом старте.
В идеальном мире конечно же всё сразу красиво делают )))

2021-03-02 15:31 UTC, Dmitry-Eremeev commented on rest_api/core.py
> +    return {"status": response.status_code, "data": response.json()}
понятно

2021-03-02 15:34 UTC, Dmitry-Eremeev commented on rest_api/rest_api.py
> +bottle.run(app, host="0.0.0.0", debug=os.getenv("REST_API_DEBUG_MODE"))
нет,
эта переменная используется для запуска контейнера и больше нигде.
Так и было задумано.
Приложение слушает все внешние интерфейсы контейнера, но пока мы не пробросим наружу, то снаружи до апи не достучаться.
И фактически я пробрасываю наружу вот так:
docker run --name rest_api --env-file rest_api/env.list -p $REST_API_HOST:$REST_API_PORT:8080 -d rest_api

В самом коде эта переменная и не должна использоваться

2021-03-02 15:35 UTC, Dmitry-Eremeev commented on rest_api/rest_api.py
> +                return bottle.HTTPResponse(status=503,
ок

2021-03-02 15:35 UTC, Dmitry-Eremeev commented on rest_api/rest_api.py
> +    result = core.get_flavors(token=bottle.request.token)
ок

2021-03-02 15:36 UTC, Dmitry-Eremeev commented on rest_api_db/Dockerfile
> +COPY init.sql /docker-entrypoint-initdb.d/
понял

2021-03-02 15:36 UTC, Dmitry-Eremeev commented on rest_api_db/init.sql
> +);
ок

2021-08-25 12:32 UTC, closed without merging